language: swift 
osx_image: xcode10.3
script:
  - xcodebuild clean build test -scheme CountOnMe -project CountOnMe.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.4' CODE_SIGN_IDENTITY=""
      CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES
after_script: bash <(curl -s https://codecov.io/bash) -t 30688173-1264-4d91-9d1b-c130c49b3225
