language: swift 
osx_image: xcode10.3
notifications:
  email: false
script:
  - xcodebuild clean build test -scheme CountOnMe -project CountOnMe.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.4' ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'CountOnMe'
